### ISSUE TITLE
Variance of a method parameter expecting callable

### ISSUE THREAD

**Issue by bwoebi** [Danack/FunctionTypes#7]
Specify, given class A `{ function foo(callable(int|string $a):int|string $b) {} }`, what types are valid in the signature for the first parameter of an overriding method B::foo.

Intuitively `class B extends A { function foo(callable(string $a):string|int|float $b) {} }` should be valid. I.e. shrinking in parameters of the callable parameters and widening of the callable return type.

**Comment by Danack** [comment]
I think this will need to wait for a future RFC. Although that would be useful, it's outside the normal use-case.
